import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const portal = fs.readFileSync(path.join(rootDir, "ta-portal.html"), "utf8");

assert.match(portal, /automatic 15-minute checkpoints/i);
assert.match(portal, /window\.location\.protocol === "file:"/);
assert.match(portal, /window\.location\.replace\(`http:\/\/localhost:3000\/ta-portal/);
assert.match(portal, /Start 1-hour demo/);
assert.match(portal, /Before interview starts/);
assert.match(portal, /minute:\s*15/);
assert.match(portal, /minute:\s*30/);
assert.match(portal, /minute:\s*45/);
assert.match(portal, /minute:\s*60/);
assert.match(portal, /session\.currentMinute === plannedEndMinute \? "finalize" : "checkpoint"/);
assert.match(portal, /setTimeout\(\(\) => advanceCopilotDemo/);
assert.match(portal, /class="copilot-live-status"/);
assert.match(portal, /The current scorecard remains available/);
assert.match(portal, /mergeCheckpointUpdate/);
assert.doesNotMatch(portal, /session\.checkpoint = null/);
assert.match(portal, /session\.checkpoints\[45\]/);
assert.match(portal, /id="copilotNotes"/);
assert.match(portal, /interviewerNotes:\s*session\.notes/);
assert.match(portal, /data-evidence-turn/);
assert.match(portal, /is-highlighted/);
assert.match(portal, /data-score-input/);
assert.match(portal, /step="0\.5"/);
assert.match(portal, /refreshFinalScoreCompletion/);
assert.match(portal, /saveButton\.disabled = session\.saved \|\| unscoredCount > 0/);
assert.match(portal, /session\.saved \? "btn-secondary" : "btn-primary"/);
assert.match(portal, /renderCopilotResult\(session, candidate\);\s*showToast\(`Final interview result saved/);
assert.match(portal, /0\.5-point steps/);
assert.match(portal, /saveInterviewResult/);
assert.match(portal, /candidate\.interviewResult/);
assert.match(portal, /Final interview result/);
assert.match(portal, /const interviewScoringGuide/);
assert.match(portal, /overallDraftScore/);
assert.match(portal, /copilot-interviewer-desk/);
assert.match(portal, /id="copilotFollowups"/);
assert.match(portal, /copilot-transcript-panel/);
assert.match(portal, /Readiness & interview/);
assert.match(portal, /Interview final/);
assert.match(portal, /Waiting for ranking/);
assert.match(portal, /interviewed:\s*"Interviewed"/);
assert.match(portal, /Generate checkpoint/);
assert.match(portal, /Refresh questions/);
assert.match(portal, /End interview now/);
assert.match(portal, /Extend to 75 min/);
assert.match(portal, /function endCopilotEarly/);
assert.match(portal, /function extendCopilotInterview/);
assert.match(portal, /plannedEndMinute < 90/);
assert.match(portal, /minute:\s*75/);
assert.match(portal, /minute:\s*90/);
assert.match(portal, /Interviewer observation source/);
assert.match(portal, /data-note-evidence/);
assert.match(portal, /latestFollowUps/);
assert.match(portal, /session\.lastFollowUps/);
assert.match(portal, /Minimize Interview Copilot to picture in picture/);
assert.match(portal, /classList\.toggle\("copilot-pip", minimized\)/);
assert.match(portal, /Picture-in-picture · browse candidate evidence freely/);
assert.match(portal, /activeCopilotCandidateId/);
assert.match(portal, /followUps\.slice\(0, 5\)/);
assert.match(portal, /\.modal-backdrop\.copilot-pip \.interviewer-notes/);
assert.match(portal, /\.modal-backdrop\.copilot-pip \.copilot-followup-dock/);
assert.match(portal, /\.mini-funnel\s*\{[^}]*grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\)/);
assert.match(portal, /AI estimate \$\{esc\(item\.score\)\}\/5/);
assert.doesNotMatch(portal, /Draft \$\{esc\(item\./);

console.log("TA Interview Copilot timeline tests passed.");
